### ISSUE TITLE
Am I missing something? 

### ISSUE THREAD

**Issue by JeffBarron** [mschwager/0wned#3]
I believe this behavior will happen when invoking sudo on any command.

**Comment by mschwager** [comment]
Hey!

You're probably not missing anything - don't overthink it. You're definitely correct that running `sudo` on a command normally gives full root privileges to that command. However, this package is highlighting that most people don't think twice before `sudo` installing a `pip` package, and that that can have devastating consequences. Given that information, this repository also tries to highlight how we can attempt to mitigate these concerns.

Hope that clears things up!

**Comment by mschwager** [comment]
To expand a little bit further: when thinking about security problems one of the steps to fixing them is having a technical solution, _but_ socializing this information and showing people the correct path is another step. I'm hoping this repository provides an easily digestable way to show some of the dangers of Python package installation and also how to do it in a safer manner.
